main: me.Plugin.Admin.Main
name: LostAdmin
version: 1.11Fixed
description: Little admin plugin 
api-version: 1.17

commands:
   heal:
      description: Heals the player.
   feed:
      description: Feeds the player.
   suicide:
      description: Kills the player.